### ISSUE TITLE
green circle lights up while the bot isn't playing 

### ISSUE THREAD

**Issue by Dramex** [KyokoBot/koe#10] opened 2020-05-14 08:26 UTC
Hi,

if the bot in the channel and it's not playing a song the green circle lights up when you join the channel. And you can even see the green circle from another channel. 

This isn't discord bug. and I can reproduce it with any bot that use lavalink dev which using latest Koe.

To reproduce it play a song then wait until it finish or seek it to the end, after it ends leave and join the channel

**Comment by ghostyinyi** [comment] 2020-05-14 08:32
looks like lavalink issue. This bug doesn't appear on kyoko that using latest Koe too.

**Comment by alula** [comment] 2020-05-14 08:34
Lavalink uses different code to sink the Opus frames (apparently they use non-immutable frames, unlike Kyoko/Koe test bot does)

**Comment by Frederikam** [comment] 2020-05-14 08:38
@alula what is the recommended way to sink audio?

**Comment by Dramex** [comment] 2020-05-14 08:41
> looks like lavalink issue. This bug doesn't appear on kyoko that using latest Koe too.

i just reproduce it using kyoko

**Comment by alula** [comment] 2020-05-14 08:42
The most efficient way that completely avoids unnecessary copies and allocations is using LavaPlayer's MutableAudioFrame and copying content from ByteBuffer attached to it (`frame.getData()` allocates an unnecessary byte array). Although I don't see this being a problem, I think the real cause is somewhere else.

**Comment by ghostyinyi** [comment] 2020-05-14 08:43
> > looks like lavalink issue. This bug doesn't appear on kyoko that using latest Koe too.
> 
> i just reproduce it using kyoko
> https://cdn.discordapp.com/attachments/701265337282330675/710410932185989161/unknown.png

This is discord bug, not Koe bug.

**Comment by alula** [comment] 2020-05-14 08:45
@ghostyinyi don't be sure, this might be Koe triggering another Discord's bug and might involve contacting Discord engineers directly, which actually happened before (with Magma too, not just Koe).

**Comment by alula** [comment] 2020-05-14 08:48
speaking/no-speaking actually triggered bugs in state management before, I'd recommend you to try out Koe from `op12-hack` branch (JitPack version `306a1e94e7`) now and check whether Discord's bug has been fixed/is related to that

**Comment by Dramex** [comment] 2020-05-14 08:53
@alula if you asking me I can try with you if you have a test bot. I'm using lavalink and i'm not sure how I should do test with it.

**Comment by alula** [comment] 2020-05-14 08:54
I'm trying to reproduce it with my testbot rn

**Comment by alula** [comment] 2020-05-14 09:36
@Frederikam I've found a bug that caused `"speaking": 0` not being sent and added a fix in https://github.com/KyokoBot/koe/releases/tag/1.0.0-beta3 could you update it in LL?

**Comment by alula** [comment] 2020-05-23 01:30
Seems to be fixed, closing

**Closed by alula** 2020-05-23 01:30 UTC
