### ISSUE TITLE
Audio playback is cut off

### ISSUE THREAD

**Issue by JellyBrick** [KyokoBot/koe#18] opened 2021-09-27 18:46 UTC
# Description

- Audio playback is cut off.
- The connection (to the Discord audio server) seems to have been lost. As the bot moves channels, the audio continues to play.

# Logs

no logs, no errors.

**Comment by alula** [comment] 2021-09-28 06:10
I think it's rather caused by how you use Koe.

Discord recently added a feature that lets you use different voice servers per channel, so when you move between channels, a full reconnection is required. You probably want to stop providing audio frames immediately upon receiving VOICE_SERVER_UPDATE, just before the websocket and UDP pipeline gets killed.

If you're using JDA-NAS with Koe, there's also $buffer_size worth packets kept in queue, so some of them will be lost when you reconnect.

**Comment by JellyBrick** [comment] 2021-09-29 03:55
> You probably want to stop providing audio frames immediately upon receiving VOICE_SERVER_UPDATE, just before the WebSocket and UDP pipeline gets killed.

No, what I'm talking about is the audio cut off abruptly. (until the bot moves to another channel)

**Comment by JellyBrick** [comment] 2022-02-14 18:25
https://github.com/freyacodes/Lavalink/issues/620#issuecomment-1036490752

**Comment by alula** [comment] 2022-09-02 01:31
I guess I can close this now

**Closed by alula** 2022-09-02 01:31 UTC
