### ISSUE TITLE
Using an already stablished connection to play music on discord

### ISSUE THREAD

**Issue by erwin1234777** [KyokoBot/koe#15] opened 2021-04-01 03:56 UTC
Using Detritus-client and lavaclient;

Heres the gist im currently using 
https://gist.github.com/erwin1234777/b6e00729ea027a9d6c8299b7d500ccca
i cannot ask for support for a feature thats still being developed, so what im asking is, instead, how do i use an already connected voice to play stuff in it.

In the gist above, i need to send 2 requests for it to be ready in a ``speaking`` state, just joining the channel would cause the bot to join as a participant(listener) not as a speaker, so those requests are necessary.

using player.play(song) does not yield any results, so im hoping for some help

Also, is there a discord server or something i can contact with?

**Comment by alula** [comment] 2021-04-01 05:16
Koe/lavalink doesn't care about details of what Discord gateway does, as long as the stage channel thing connects to voice channel in identical way as normal voice channels do (which apparently does, I haven't checked anything yet) the issue for the thing you want to do is on side of your code or the library that talks to lavalink.

**Comment by erwin1234777** [comment] 2021-04-01 05:43
@alula i managed to work around it by first connecting to the channel via lavalink and THEN requesting the speaker access.
However, even if minor, this cuts about a second or two of the audio until it starts speaking in the channel. So my question still persists if theres a way to use a voice connection beforehand(i was fowarded here by the lavaclient dev, the lib im using)

**Comment by alula** [comment] 2021-04-01 05:51
I thibk that your issue seems to be caused by Lavalink trying to send the audio data too early and Koe has nothing to do with that - it's only purpose is to manage connections to Discord's voice servers and sending proper RTP packets. It doesn't care about client state at all, if you're muted, Discord will simply not forward any incoming packets and Koe has nothing to do with that.

**Comment by alula** [comment] 2021-04-01 05:53
The solution you're likely looking for is letting Lavalink add the song or whatever to queue without immediately playing it, request speaker powers and once you got it tell Lavalink to start sending the audio data.

**Comment by alula** [comment] 2021-04-01 05:53
Also I'm closing the issue since it has nothing to do with Koe

**Closed by alula** 2021-04-01 05:54 UTC
